# Generated by Django 5.0.2 on 2024-02-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviços', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='tipo',
            field=models.TextField(max_length=10),
        ),
    ]
