# Generated by Django 5.0.2 on 2024-02-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviços', '0003_alter_servico_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='tipo_cliente',
            field=models.CharField(choices=[('Dentista', 'Dentista'), ('Protetico', 'Protetico'), ('Particular', 'Particular')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
