# Generated by Django 5.0.2 on 2024-02-13 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviços', '0004_servico_tipo_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='tipo_cliente',
        ),
    ]
