# Generated by Django 5.0.2 on 2024-02-14 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviços', '0007_servico_detalhes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='detalhes',
        ),
    ]
