# Generated by Django 5.0.2 on 2024-02-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviços', '0008_remove_servico_detalhes'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='detalhes',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
