# Generated by Django 5.0.2 on 2024-02-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviços', '0009_servico_detalhes'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='status',
            field=models.CharField(blank=True, choices=[('Pago', 'Pago'), ('Não pago', 'Não pago')], max_length=20, null=True),
        ),
    ]
