# Generated by Django 5.0.2 on 2024-02-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviços', '0010_servico_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='data_entrada',
            new_name='data_de_entrada',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='tipo_cliente',
            new_name='tipo_do_cliente',
        ),
        migrations.AddField(
            model_name='servico',
            name='nome_do_paciente',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
